#!/bin/bash

SPEC=/home/user/cypress/integration/navigate.spec.js
RESULTS=/home/user/results.json

# Check if "Start learning" button is clicked
grep -Ez "\.get\(.a\.play.\).*\.click\(\)" $SPEC

if [ $? == 1 ]; then
  fail-message "The 'Start learning' button isn't clicked (hint: the first a.play element)"
  exit 1
fi

# Check if the correct URL is verified
grep -Ez "\.url\(\)[[:space:]]*\.should\(.eq., ?.https:\/\/play\.instruqt\.com\/public.\)" $SPEC

if [ $? == 1 ]; then
  fail-message "The URL isn't verified using should('eq', 'https://play.instruqt.com/public')"
  exit 1
fi

/home/user/node_modules/cypress/bin/cypress run > results.json

grep -Ez "XVFB" $RESULTS

if [ $? == 1 ]; then
  fail-message "Test result is failed"
  exit 1
fi
# Check if the test has been executed successfully
# TODO
# grep logfile / reportje?

exit 0