#!/bin/bash

SPEC=/home/user/cypress/integration/navigate.spec.js

# Check if "Start learning" button is clicked
grep -Ez "\.get\(.a\.play.\)[[:space:]]*\.click\(\)" $SPEC

if [ $? == 1 ]; then
  fail-message "The 'Start learning' button isn't clicked (element a.play)"
fi

# Check if the correct URL is verified
grep -Ez "\.url\(\)[[:space:]]*\.should\(.eq., ?.https:\/\/play\.instruqt\.com\/public.\)" $SPEC

if [ $? == 1 ]; then
  fail-message "The URL isn't verified using should('eq', 'https://play.instruqt.com/public')"
fi

# Check if the test has been executed successfully
# TODO
# grep logfile / reportje?

exit 0