#!/bin/sh

cat > /home/user/cypress/integration/navigate.spec.js <<EOF
describe('Navigation', () => {
  beforeEach(() => {
    cy.visit('https://instruqt.com')
  })

  // https://on.cypress.io/interacting-with-elements

  it('Start learning should take you to the track overview', () => {

  })
})

EOF