#!/bin/bash

echo "Waiting for Cypress..."
TIMEOUT=1
until [ -d "/home/user/cypress/integration" ] || [ $TIMEOUT == 60 ]; then
  sleep 1
  let TIMEOUT=$TIMEOUT+1
fi

echo "Creating template..."

cat > /home/user/cypress/integration/navigate.spec.js <<EOF
describe('Navigation', () => {
  beforeEach(() => {
    cy.visit('https://instruqt.com')
  })

  // https://on.cypress.io/interacting-with-elements

  it('Start learning should take you to the track overview', () => {

  })
})
EOF

if [ $? == 1 ]; then
  echo "Something went wrong when creating a template spec file"
  exit 1
fi

exit 0