template: containers
configuration:
  Containers:
  - Environment: {}
    Image: tettaji/instruqt-cypress:latest
    Name: cypress
    Ports:
    - 9000
    - 6800
    Resources:
      Memory: 2048
    Shell: su - user
