template: containers
configuration:
  Containers:
  - Environment: {}
    Image: gcr.io/instruqt/cypress
    Name: cypress
    Ports:
    - 9000
    Resources:
      Memory: 1024
    Shell: su - user
